### ISSUE TITLE
Doubt asks for advice

### ISSUE THREAD

**Issue by zd-yaping-guo** [stevenmhunt/testjam-io#31]
I just want to use tools inherited to electron to develop client products without Firebase. How can I do that?

**Comment by stevenmhunt** [comment]
I didn't design Test Jam to run outside of Firebase since it is a fun hobby project I run for the community for free. If you want to design applications that can be deployed in Firebase but also Electron or even some other cloud provider, I would recommend using TypeScript while abstracting all platform-specific code behind sensible interfaces so that you can implement them for each specific platform. This also helps with automated testing as well.
